kumuluzee:
  name: rsostream-storlyze
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  server:
#    base-url: http://169.51.13.160 # zunanji URL
    base-url: http://localhost # zunanji URL
    http:
      port: 8085
  discovery:
    etcd:
#      hosts: http://etcd:2379
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
#    logs:
#      enabled: true
#      period-s: 30
#      level: TRACE
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /v1/tcp/*
      - name: premetheus-endpoint
        url-pattern: /prometheus/*
  fault-tolerance:
    config:
      watch-enabled: true
      watch-properties: timeout.value,circuit-breaker.failure-ratio
    circuit-breaker:
      delay: 3s
    crud:
      bulkhead:
        value: 5
      timeout:
        value: 2500ms
      circuit-breaker:
        request-volume-threshold: 10
        failure-ratio: 0.3
        metrics:
          rolling-window:
            size: 8s
            buckets: 4
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: TRACE
      period-s: 30
#    logstash: #TODO
#      address: 221e8a85-d5ce-40e4-a708-057e7c7d7e68-ls.logit.io
#      port: 14880
#      period-s: 15
    checks:
      disk-space-health-check:
        threshold: 100000000
#      http-health-check:
#        - connection-url: http://localhost:8080/v1/tcp # Please change this into something more meaningful.
#      mongo-health-check:
#        connection-url: mongodb://rso:123456@ds247317.mlab.com:47317/rso-db?serverSelectionTimeoutMS=2000
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="rso-tcp">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="221e8a85-d5ce-40e4-a708-057e7c7d7e68-ls.logit.io" port="14880"
                                                                                         protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default util -->
                          <Root level="all">
                              <AppenderRef ref="console" level="debug"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'
rabbit-mq:
  host: gopher.rmq.cloudamqp.com
  username: pmhwkvgq
  password: 0wV5qBOCns70ZMQBL9qZ6MvfjgQwtRMn
  routing-key: tcp-q
  exchange-name: ''
mongo-db:
  uri: mongodb://rso:123456@ds247317.mlab.com:47317/rso-db
  username: rso
  password: 123456
  host: ds247317.mlab.com
  port: 47317
  db: rso-db
  device-collection: Devices
  settings-collection: DeviceSettings
  sensor-data-collection: SensorData
crud:
  service-name: rsostream-crud
  version: 1.0.0
  environment: dev
  reading-base-uri: v1/reading/
  device-base-uri: v1/device/
# ETCD kubernetes deployment -> github rso-customers @ jmezna