apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
    name: access
  - port: 15672
    protocol: TCP
    targetPort: 9000
    name: web-console
  selector:
    app: rabbitmq
