apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rso-rabbit
    spec:
      containers:
      - command:
        - --hostname
        - rabbitmq
        - --name
        - rabbitmq
        image: rsostream/rabbitmq:latest
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: access
          protocol: TCP
        - containerPort: 15672
          name: web-console
          protocol: TCP
